export const database = [
  {
    id: 1,
    name: "marble toffee",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit amet. Pharetra et ultrices neque ornare. Vivamus at augue eget arcu dictum varius duis at consectetur.",
    variations: ["round", "diamond", "boxy"],
    type: "ring",
    categories: ["chunky", "minimalist", "new arrival"],
    photos: ["https://i.imgur.com/YY9kCyW.png", "https://i.imgur.com/E5HOYa2.png"],
    size: 19,
    price: 12,
    sale: false,
    salePrice: null
  },
  {
    id: 2,
    name: "clear waters",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl vel pretium lectus quam.",
    type: "ring",
    variations: ["small", "round", "boxy", "geometric"],
    categories: ["chunky", "minimalist"],
    photos: ["https://i.imgur.com/E5HOYa2.png"],
    size: 14,
    price: 10,
    sale: false,
    salePrice: null
  },
  {
    id: 3,
    name: "old smokey",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit amet. Pharetra et ultrices neque ornare. Vivamus at augue eget arcu dictum varius duis at consectetur.",
    type: "ring",
    variations: ["onyx", "amber", "ivory"],
    categories: ["chunky", "minimalist"],
    photos: ["https://i.imgur.com/rv030lH.png"],
    size: 19,
    price: 12,
    sale: false,
    salePrice: null
  },
  {
    id: 4,
    name: "fortune fortune",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl vel pretium lectus quam.",
    type: "ring",
    variations: ["emerald", "ochre", "ivory", "pearl"],
    categories: ["chunky", "minimalist", "new arrival"],
    photos: ["https://i.imgur.com/W2QEm9P.png"],
    size: 18,
    price: 12,
    sale: false,
    salePrice: null
  },
  {
    id: 5,
    name: "button babe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl vel pretium lectus quam.",
    type: "ring",
    variations: ["baby blue"],
    categories: ["chunky", "fun"],
    photos: ["https://i.imgur.com/xXYzHaW.png"],
    size: 19,
    price: 10,
    sale: true,
    salePrice: 7
  },
  {
    id: 6,
    name: "marble caramel",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl vel pretium lectus quam.",
    variations: ["round", "diamond", "boxy"],
    type: "ring",
    categories: ["chunky", "minimalist", "new arrival"],
    photos: ["https://i.imgur.com/YY9kCyW.png", "https://i.imgur.com/E5HOYa2.png"],
    size: 19,
    price: 12,
    sale: false,
    salePrice: null
  },
  {
    id: 7,
    name: "clear waters",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl vel pretium lectus quam.",
    type: "ring",
    variations: ["small", "round", "boxy", "geometric"],
    categories: ["chunky", "minimalist"],
    photos: ["https://i.imgur.com/E5HOYa2.png"],
    size: 22,
    price: 10,
    sale: false,
    salePrice: null
  },
  {
    id: 8,
    name: "old smokey",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl vel pretium lectus quam.",
    type: "ring",
    variations: ["onyx", "amber", "ivory"],
    categories: ["chunky", "minimalist"],
    photos: ["https://i.imgur.com/rv030lH.png"],
    size: 17,
    price: 12,
    sale: false,
    salePrice: null
  },
  {
    id: 9,
    name: "fortune fortune",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl vel pretium lectus quam.",
    type: "ring",
    variations: ["emerald", "ochre", "ivory", "pearl"],
    categories: ["chunky", "minimalist", "new arrival"],
    photos: ["https://i.imgur.com/W2QEm9P.png"],
    size: 16,
    price: 12,
    sale: false,
    salePrice: null
  },
  {
    id: 10,
    name: "button babe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl vel pretium lectus quam.",
    type: "ring",
    variations: ["baby blue"],
    categories: ["chunky", "fun"],
    photos: ["https://i.imgur.com/xXYzHaW.png"],
    size: 20,
    price: 10,
    sale: true,
    salePrice: 7
  },
  {
    id: 11,
    name: "marble caramel",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl vel pretium lectus quam.",
    variations: ["round", "diamond", "boxy"],
    type: "ring",
    categories: ["chunky", "minimalist", "new arrival"],
    photos: ["https://i.imgur.com/YY9kCyW.png", "https://i.imgur.com/E5HOYa2.png"],
    size: 22,
    price: 12,
    sale: false,
    salePrice: null
  },
  {
    id: 12,
    name: "clear waters",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl vel pretium lectus quam.",
    type: "ring",
    variations: ["small", "round", "boxy", "geometric"],
    categories: ["chunky", "minimalist"],
    photos: ["https://i.imgur.com/E5HOYa2.png"],
    size: 15,
    price: 10,
    sale: false,
    salePrice: null
  },
  {
    id: 13,
    name: "old smokey",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl vel pretium lectus quam.",
    type: "ring",
    variations: ["onyx", "amber", "ivory"],
    categories: ["chunky", "minimalist"],
    photos: ["https://i.imgur.com/rv030lH.png"],
    size: 17,
    price: 12,
    sale: false,
    salePrice: null
  },
  {
    id: 14,
    name: "fortune fortune",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl vel pretium lectus quam.",
    type: "ring",
    variations: ["emerald", "ochre", "ivory", "pearl"],
    categories: ["chunky", "minimalist", "new arrival"],
    photos: ["https://i.imgur.com/W2QEm9P.png"],
    size: 16,
    price: 12,
    sale: false,
    salePrice: null
  },
  {
    id: 15,
    name: "button babe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl vel pretium lectus quam.",
    type: "ring",
    variations: ["baby blue"],
    categories: ["chunky", "fun"],
    photos: ["https://i.imgur.com/xXYzHaW.png"],
    size: 18,
    price: 10,
    sale: true,
    salePrice: 7
  }
];

export const categories = ["minimalist", "classic", "chunky", "fun", "colours"];